sources:
  - name: TechCrunch LATAM
    url: https://techcrunch.com/tag/latin-america/feed/
  - name: LatAmList
    url: https://latamlist.com/feed/
  - name: Rest of World
    url: https://restofworld.org/feed/

# Crunchbase: обычно нужен API/платный доступ. Добавишь отдельным адаптером позже.
